server:
  port: 9000

spring:
  application:
    name: user-service-provider
  cloud:
    nacos:
      server-addr: nacos:8848

feign-exception:
  debug: true
  provider:
    enable: true
  consumer:
    enable: true
